# Total simulation time (in seconds)
simulation_time_s: 1000
# Client Poisson rate arrival (in 1/seconds)
poisson_rate: 0.1
# Training section length (in meters)
road_length_m: 600
# Min and max client speed (in kilometer per hour)
min_speed_kph: 30
max_speed_kph: 60
# Random seed for reproductibility
numpy_seed: 42
# Round duration (in seconds)
round_duration_s: 60
# Min and max client number of data
min_n_data: 100
max_n_data: 1000
# Number of random data classes per client (between 1 and 10)
n_sub_classes: 8
min_cpu_hertz: 1.0e+9
max_cpu_hertz: 2.0e+9
batch: 16
n_local_epochs: 5
n_cpu_cycles_per_data: 3.0e+5
effective_capacitance: 1.0e-27
snr_db_min: 5
snr_db_max: 20
bandwidth_hz: 100.0e+6
tx_power_w: 10
model_precision: 16
learning_rate: 1.0e-3
momentum: 0.9
weight_decay: 5.0e-4
data_path: data/cifar10
